name: "build & deploy: api (v2)"
on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build-api-v2.yml"
      - "v2/Cargo.*"
      - "v2/thaliak-api/**"
      - "v2/thaliak-common/**"
      - "v2/thaliak-types/**"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          submodules: recursive
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: v2
          file: ./thaliak-api/Dockerfile
          push: true
          tags: ghcr.io/crystallinetools/thaliak-api:v2
      - name: Deploy to production server
        uses: appleboy/ssh-action@v1.2.3
        with:
          host: "${{ secrets.REMOTE_HOST }}"
          port: 22
          username: "${{ secrets.REMOTE_USER }}"
          key: "${{ secrets.REMOTE_SSH_KEY }}"
          script: deploy api-v2
